---

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Make sure env vars are set
  debug:
    msg: "'{{ lookup('env', 'TYPEORM_HOST') }}' is the DB Host name."