---
- name: Copy artifacts
  become: yes
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Unarchive artifact
  become: yes
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/

- name: Start app
  become: yes
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm -- start
