---
- name: Copy artifacts
  become: yes
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Unarchive artifact
  become: yes
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/
    remote_src: yes

- name: verify artifact
  become: yes
  shell: |
    ls /home/ubuntu/ -la
  register: result

- name: Print return information from the previous task
  debug:
    var: result
    verbosity: 2

- name: Start app
  become: yes
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm -- start
