---
- name: Copy artifacts
  become: yes
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Unarchive artifact
  become: no
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/
    remote_src: yes

- name: Make sure env vars are set
  debug:
    msg: "'{{ lookup('env', 'TYPEORM_HOST') }}' is the DB Host name."


- name: Start app
  become: yes
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm -- start
  register: result

- name: Print return information from the previous task
  debug:
    var: result
